### ISSUE TITLE
JavaScript issues?

### ISSUE THREAD

**Issue by spickermann** [krautcomputing/rubydocs#7] opened 2016-04-27 12:28 UTC
Hey there, 

I am not sure if this is just on my end or if there is a JavaScript problem.

When I search for a method and then click on the method's name, both frames load the documentation and the list on the left shows the same content (see screenshot):

<img width="976" alt="bildschirmfoto 2016-04-27 um 14 26 42" src="https://cloud.githubusercontent.com/assets/393096/14852018/2237efac-0c84-11e6-84dd-ffa938824a09.png">

This seems to happen in both the online and the downloaded version. 

Furthermore I notice that the list on the left doesn't show anymore in what class the method was found (see screenshot)

<img width="841" alt="bildschirmfoto 2016-04-28 um 10 59 50" src="https://cloud.githubusercontent.com/assets/393096/14880698/91f341aa-0d30-11e6-993b-8f4d460a015a.png">

Please ping me if you need further information or might need a hand.

**Comment by manuelmeurer** [comment] 2016-04-28 14:04
Hmm, that's weird. I did indeed change the sdoc template [to include <a> instead of <h1> elements in the sidebar](https://github.com/zzak/sdoc/commit/1152fa14358c24ea377ffcdee659e84850da9b77), but the links should of course only be opened in the main area, [not in the sidebar](https://github.com/zzak/sdoc/commit/1152fa14358c24ea377ffcdee659e84850da9b77#diff-b76bfd12e3e6bee2c2e64915df114875R291). Can you check your console if JS loading is blocked somehow? Do you use any ad blocking plugins?

The problem that the class names are not displayed anymore is that I forgot the search results when changing the <h1>s to <a>s in the sidebar... will fix that in the sdoc project.

Thanks for reporting this! 👍

**Comment by spickermann** [comment] 2016-04-28 14:13
I use ad blocking plugins in Chrome. But the developer console doesn't show js errors. And there are no files blocked in the network tab. Furthermore I was also able to reproduce this behavior with a Firefox browser which has no plugins installed. Both browser are the lastest version.

**Comment by manuelmeurer** [comment] 2016-04-28 14:16
It only happens when you search first, right? If you simply click on an entry in the sidebar without searching, does it work? 😄

**Comment by spickermann** [comment] 2016-04-28 14:20
Confirm. This happens only when I search first. Using the tree works fine. Unfortunately I usually do not use the tree, I always use the search function.

It feels to me like there is a `e.preventDefault();` missing in the search results. But I am not familiar with the code, therefore I am not sure where to look.

**Comment by manuelmeurer** [comment] 2016-04-29 13:57
It should be fixed now. Could you check with these docs that the issue is gone for you: http://docs.rubydocs.org/ruby-2-3-1-rails-5-0-0-beta4/

**Comment by spickermann** [comment] 2016-04-29 14:16
Great, it works like expected. Thank you. 

There is just a minor encoding issue. Please have a look at the description below `presence`, there is an `'` encoded as `&39;`. 

<img width="306" alt="bildschirmfoto 2016-04-29 um 15 59 20" src="https://cloud.githubusercontent.com/assets/393096/14918436/3994da74-0e24-11e6-817e-4c4cecdd0f56.png">

Thanks again for fixing this. And I am very thankful for your effort in running and maintaining this site. The downloadable doc is a very important part of my toolchain.

**Comment by manuelmeurer** [comment] 2016-04-29 14:48
Great! 😄 
The encoding issue was already present before I think... must be fixed in sdoc as well.

Great to hear you find RubyDocs helpful! This kind of feedback is what keeps me motivated to work on the site! 😸

**Closed by manuelmeurer** 2016-04-29 14:48 UTC

**Comment by spickermann** [comment] 2016-04-30 06:43
I noticed that both `ruby-2-2-5-rails-4-2-6` versions (online and downloadable) are also affected. It seems like all bundles that were generated between the last deploy and the fix yesterday are broken and must be re-generated.

**Comment by manuelmeurer** [comment] 2016-04-30 07:56
Yep, will start the process today and then all docs will be regenerated one by one... this might take a few days though. 😄
